package api

import (
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"net/http"

	"github.com/IzE-PewPewPew/DK-AgentMemory/internal/logx"
	"github.com/IzE-PewPewPew/DK-AgentMemory/internal/store"
)

// Error codes. Stable strings, because clients switch on them and a renamed
// code is a breaking change even when the status stays the same.
const (
	CodeBadRequest   = "bad_request"
	CodeUnauthorized = "unauthorized"
	CodeForbidden    = "forbidden"
	CodeNotFound     = "not_found"
	CodeConflict     = "conflict"
	CodeRateLimited  = "rate_limited"
	CodeUnavailable  = "unavailable"
	CodeInternal     = "internal"
)

// ErrorBody is the shape of every error response.
//
// Every response in this API has a JSON body -- including 404 and 500, and
// including responses generated by the framework rather than by a handler. A
// bare 404 with an empty body is indistinguishable from a reverse proxy that
// never routed the request, and debugging that difference has cost more time
// than any feature in this project has saved.
type ErrorBody struct {
	Error     string `json:"error"`
	Message   string `json:"message"`
	RequestID string `json:"request_id,omitempty"`
	// Hint appears when there is a concrete next action. It is omitted rather
	// than filled with "please try again".
	Hint string `json:"hint,omitempty"`
}

// APIError is an error carrying an HTTP status.
type APIError struct {
	Status  int
	Code    string
	Message string
	Hint    string
	// Err is the underlying cause. It is logged and never sent to the client:
	// driver messages leak schema and connection details.
	Err error
	// Headers are set on the response. Used for Retry-After, which is part of
	// the contract of a 429 rather than decoration.
	Headers map[string]string
}

func (e *APIError) Error() string {
	if e.Err != nil {
		return fmt.Sprintf("%s: %s: %v", e.Code, e.Message, e.Err)
	}
	return fmt.Sprintf("%s: %s", e.Code, e.Message)
}

func (e *APIError) Unwrap() error { return e.Err }

// Constructors for the statuses handlers actually return.

func badRequest(format string, args ...any) *APIError {
	return &APIError{Status: http.StatusBadRequest, Code: CodeBadRequest, Message: fmt.Sprintf(format, args...)}
}

func notFound(what string) *APIError {
	return &APIError{Status: http.StatusNotFound, Code: CodeNotFound, Message: what + " not found"}
}

func forbidden(msg string) *APIError {
	return &APIError{Status: http.StatusForbidden, Code: CodeForbidden, Message: msg}
}

func conflict(msg string) *APIError {
	return &APIError{Status: http.StatusConflict, Code: CodeConflict, Message: msg}
}

func unavailable(msg string, err error) *APIError {
	return &APIError{Status: http.StatusServiceUnavailable, Code: CodeUnavailable, Message: msg, Err: err}
}

func internal(err error) *APIError {
	return &APIError{
		Status:  http.StatusInternalServerError,
		Code:    CodeInternal,
		Message: "internal error",
		Hint:    "quote the request_id when reporting this",
		Err:     err,
	}
}

// fromStore maps store sentinels to HTTP errors, so handlers do not each invent
// their own translation.
func fromStore(err error, what string) *APIError {
	switch {
	case err == nil:
		return nil
	case errors.Is(err, store.ErrNotFound):
		return notFound(what)
	case errors.Is(err, store.ErrConflict):
		return conflict(err.Error())
	case errors.Is(err, store.ErrForbidden):
		return forbidden(err.Error())
	default:
		return internal(err)
	}
}

// writeJSON sends a JSON body with the given status.
func writeJSON(w http.ResponseWriter, status int, v any) {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.Header().Set("X-Content-Type-Options", "nosniff")
	w.WriteHeader(status)
	if v == nil {
		_, _ = w.Write([]byte("{}"))
		return
	}
	enc := json.NewEncoder(w)
	enc.SetEscapeHTML(false)
	if err := enc.Encode(v); err != nil {
		// The status line is already sent, so this cannot become an error
		// response. Logging it is all that remains.
		slog.Default().Error("encoding response body", "error", err)
	}
}

// writeError renders an error as JSON and logs the cause.
func (s *Server) writeError(w http.ResponseWriter, r *http.Request, err error) {
	var apiErr *APIError
	if !errors.As(err, &apiErr) {
		apiErr = internal(err)
	}

	for k, v := range apiErr.Headers {
		w.Header().Set(k, v)
	}

	reqID := logx.RequestID(r.Context())
	body := ErrorBody{
		Error:     apiErr.Code,
		Message:   apiErr.Message,
		RequestID: reqID,
		Hint:      apiErr.Hint,
	}

	log := logx.From(r.Context(), s.log)
	if apiErr.Status >= 500 {
		log.Error("request failed",
			"status", apiErr.Status, "code", apiErr.Code,
			"method", r.Method, "path", r.URL.Path, "error", apiErr.Error())
	} else {
		log.Debug("request rejected",
			"status", apiErr.Status, "code", apiErr.Code,
			"method", r.Method, "path", r.URL.Path, "message", apiErr.Message)
	}

	writeJSON(w, apiErr.Status, body)
}

// decodeJSON reads a request body into v with a size limit.
func decodeJSON(w http.ResponseWriter, r *http.Request, v any) error {
	// 32 MiB. Large enough for a batch of observations, small enough that a
	// malformed or hostile request cannot exhaust memory. Bulk paths stream
	// NDJSON instead of buffering, so nothing legitimate is near this.
	r.Body = http.MaxBytesReader(w, r.Body, 32<<20)

	dec := json.NewDecoder(r.Body)
	dec.DisallowUnknownFields()
	if err := dec.Decode(v); err != nil {
		var maxErr *http.MaxBytesError
		if errors.As(err, &maxErr) {
			return badRequest("request body exceeds %d bytes; use the NDJSON import endpoint for bulk data", maxErr.Limit)
		}
		return badRequest("malformed JSON body: %v", err)
	}
	return nil
}
